# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Unstable Build
email: lucastorri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a place to record my learnings, nothing fancy.
baseurl: "/unstable-build.s3.amazonaws.com" # the subpath of your site, e.g. /blog
url: "https://s3.amazonaws.com/unstable-build.s3.amazonaws.com" # the base hostname & protocol for your site
twitter_username: lucastorri
github_username:  lucastorri

# Build settings
markdown: kramdown

# Outputting
permalink: /:year/:month/:day/:title.html
