
# Site settings
title: Unstable Build
email: lucastorri@gmail.com
description: >
  A place to record my learnings.
baseurl: ""
url: "http://www.unstablebuild.com"
twitter_username: lucastorri
github_username:  lucastorri

# Build settings
markdown: kramdown

# Input
exclude: [vendor, Gemfile*]

# Output
permalink: /:year/:month/:day/:title.html

# Plugins
gems:
  - jekyll-sitemap

