
# Site settings
title: Unstable Build
email: lucastorri@gmail.com
description: >
  Just a place to record my learnings, nothing fancy.
baseurl: ""
url: "http://www.unstablebuild.com"
twitter_username: lucastorri
github_username:  lucastorri

# Build settings
markdown: kramdown

# Input
exclude: [vendor]

# Output
permalink: /:year/:month/:day/:title.html

# Index
algolia:
  application_id: "1T1R4DS24U"
  index_name: "unstablebuild"
