#!/bin/bash

source "`dirname "$0"`/_settings"

$GEM_EXEC_DIR/bundle install

$JEKYLL_CMD build
$GEM_EXEC_DIR/s3_website push
$JEKYLL_CMD algolia push

readonly blog_url=`ruby -e "require 'yaml'; print YAML.load(File.open('_config.yml'))['url']"`
echo "New version deployed to $blog_url"
