#!/bin/bash

source "`dirname "$0"`/_settings"

readonly post_title="$1"

slugify() {
    local title="$1"
    
    echo "$title" \
        | iconv -f 'utf8' -t 'ascii//TRANSLIT//IGNORE' \
        | tr '[:upper:]' '[:lower:]' \
        | tr -cd "[:alnum:][:space:]" \
        | tr -cs '[:alnum:]\n' '-'
}

echo "---
layout: post
title: \"$post_title\"
date: `date +'%F %T %z'`
categories: update
---
" > "_posts/$(date +'%F')-$(slugify "$post_title").markdown"
