#!/bin/bash

source "`dirname "$0"`/_settings"

readonly post_title="$1"
readonly new_post_dir="_drafts"

slugify() {
    local title="$1"
    
    echo "$title" \
        | iconv -f 'utf8' -t 'ascii//TRANSLIT//IGNORE' \
        | tr '[:upper:]' '[:lower:]' \
        | tr -cd "[:alnum:][:space:]" \
        | tr -cs '[:alnum:]\n' '-'
}

readonly new_post_file="$new_post_dir/$(date +'%F')-$(slugify "$post_title").markdown"

echo "---
layout: post
title: \"$post_title\"
date: `date +'%F %T %z'`
categories: update
---
" > "$new_post_file"

echo $new_post_file

